import {useEffect,useState} from 'react';
import api from '../api/client';
export default function Inventory(){
 const [rows,setRows]=useState([]),[alerts,setAlerts]=useState(null),[form,setForm]=useState({sku:'',name:'',category:'Thảo dược',unit:'viên',alert_low:10,image:''});
 const load=async()=>setRows((await api.get('/inventory/items')).data.data||[]);
 useEffect(()=>{load();api.get('/inventory/alerts').then(r=>setAlerts(r.data.data))},[]);
 const add=async e=>{e.preventDefault();await api.post('/inventory/items',form);setForm({sku:'',name:'',category:'Thảo dược',unit:'viên',alert_low:10,image:''});load()};
 return <div><h1 className="text-2xl font-bold mb-4">Kho dược</h1><div className="grid lg:grid-cols-3 gap-4 mb-4"><div className="bg-white rounded-xl p-4"><b>SKU</b><div className="text-2xl">{rows.length}</div></div><div className="bg-white rounded-xl p-4"><b>Sắp hết hạn</b><div className="text-2xl">{alerts?.expiringSoon??'—'}</div></div><div className="bg-white rounded-xl p-4"><b>Giá trị kho</b><div className="text-2xl">{Number(alerts?.totalValue||0).toLocaleString()}đ</div></div></div>
 <form onSubmit={add} className="bg-white rounded-xl p-4 mb-4 grid md:grid-cols-6 gap-2"><input required placeholder="SKU" className="border rounded px-3 py-2" value={form.sku} onChange={e=>setForm({...form,sku:e.target.value})}/><input required placeholder="Tên" className="border rounded px-3 py-2" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="Nhóm" className="border rounded px-3 py-2" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/><input placeholder="Đơn vị" className="border rounded px-3 py-2" value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}/><input placeholder="URL Ảnh" className="border rounded px-3 py-2" value={form.image} onChange={e=>setForm({...form,image:e.target.value})}/><button className="bg-emerald-600 text-white rounded">+ Thêm</button></form>
 <div className="bg-white rounded-xl shadow overflow-auto"><table className="min-w-full text-sm"><thead><tr className="bg-gray-50 border-b">{['Ảnh','SKU','Tên','Nhóm','Đơn vị','Tồn','Giá TB','Mức cảnh báo'].map(x=><th className="p-3 text-left" key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr className="border-b" key={r.id}><td className="p-2"><div className="w-12 h-10 bg-gray-100 rounded overflow-hidden">{r.image && <img src={r.image} className="w-full h-full object-cover" />}</div></td><td className="p-3">{r.sku}</td><td className="p-3">{r.name}</td><td className="p-3">{r.category}</td><td className="p-3">{r.unit}</td><td className="p-3">{r.qty}</td><td className="p-3">{Number(r.avg_cost||0).toLocaleString()}</td><td className="p-3">{r.alert_low}</td></tr>)}</tbody></table></div></div>;
}
