import {useEffect,useState} from 'react';
import api from '../api/client';
export default function Patients(){
 const [rows,setRows]=useState([]),[open,setOpen]=useState(false),[editing,setEditing]=useState(null),[form,setForm]=useState({full_name:'',gender:'male',birth_date:'',phone:'',email:'',address:'',allergies:'',chronic_diseases:''});
 const load=async()=>setRows((await api.get('/patients')).data.data||[]); useEffect(()=>{load()},[]);
 const save=async e=>{e.preventDefault(); if(editing) await api.put('/patients/'+editing.id,form); else await api.post('/patients',form);setOpen(false);setEditing(null);load()};
 const edit=r=>{setEditing(r);setForm({...form,...r});setOpen(true)};
 return <div><div className="flex justify-between mb-4"><h1 className="text-2xl font-bold">Bệnh nhân</h1><button className="bg-emerald-600 text-white px-4 py-2 rounded" onClick={()=>{setEditing(null);setForm({full_name:'',gender:'male',birth_date:'',phone:'',email:'',address:'',allergies:'',chronic_diseases:''});setOpen(true)}}>+ Thêm</button></div>
 <div className="bg-white rounded-xl shadow overflow-auto"><table className="min-w-full text-sm"><thead><tr className="bg-gray-50 border-b">{['Mã','Họ tên','Giới tính','SĐT','Địa chỉ',''].map((x,i)=><th className="p-3 text-left" key={i}>{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr className="border-b" key={r.id}><td className="p-3">{r.patient_code}</td><td className="p-3">{r.full_name}</td><td className="p-3">{r.gender}</td><td className="p-3">{r.phone}</td><td className="p-3">{r.address}</td><td className="p-3"><button className="text-blue-600" onClick={()=>edit(r)}>Sửa</button></td></tr>)}</tbody></table></div>
 {open&&<div className="fixed inset-0 bg-black/40 flex items-center justify-center p-4"><form onSubmit={save} className="bg-white rounded-xl p-6 w-full max-w-2xl grid md:grid-cols-2 gap-3"><h2 className="md:col-span-2 text-xl font-semibold">Thông tin bệnh nhân</h2>{[['full_name','Họ tên'],['birth_date','Ngày sinh'],['phone','Điện thoại'],['email','Email'],['address','Địa chỉ'],['allergies','Dị ứng'],['chronic_diseases','Bệnh nền']].map(([k,l])=><label key={k}><span>{l}</span><input className="w-full border rounded px-3 py-2" value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label><span>Giới tính</span><select className="w-full border rounded px-3 py-2" value={form.gender} onChange={e=>setForm({...form,gender:e.target.value})}>{['male','female','other'].map(x=><option key={x}>{x}</option>)}</select></label><div className="md:col-span-2 flex justify-end gap-2"><button type="button" onClick={()=>setOpen(false)} className="border px-4 py-2 rounded">Hủy</button><button className="bg-emerald-600 text-white px-4 py-2 rounded">Lưu</button></div></form></div>}</div>;
}
